# Generated by Django 5.2 on 2025-04-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(max_length=100)),
                ('sensor_name', models.CharField(max_length=100)),
                ('device_addr', models.CharField(max_length=100)),
                ('sensor_val', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('sensor_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('workers', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'enriched_sensor_data',
            },
        ),
        migrations.CreateModel(
            name='HubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.TextField(unique=True)),
                ('owner', models.JSONField(default=list)),
                ('workers', models.JSONField(default=list)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hub_config',
            },
        ),
        migrations.CreateModel(
            name='RawSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.TextField()),
                ('sensor_name', models.TextField()),
                ('device_addr', models.TextField()),
                ('sensor_val', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('sensor_id', models.TextField()),
            ],
            options={
                'db_table': 'raw_sensor_data',
            },
        ),
    ]
