# Generated by Django 5.2 on 2025-04-29 23:36

import sensor_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconfig',
            name='hub_id',
            field=models.CharField(default=sensor_data.models.generate_hub_id, editable=False, max_length=20, unique=True),
        ),
    ]
